### PR TITLE
Add initial 'spatial mode' option

### PR DESCRIPTION
**Pull request by moochris**
Add an option for a 'spatial mode' (might be a more user friendly description here) in the preferences.

This enables the storing of window position and size in extended attributes for the particular folder open. The folders are opened in new windows and will remember the position and size if you move and resize them.

Signed-off-by: Chris Moore <chris@mooreonline.org>

### CODE REVIEW

**Comment by probonopd** [comment]
Very cool @moochris, it's a great start. 👍 
I will comment in the ticket about some additional aspects we need to think about.

image

**Comment by moochris** [comment]
You'll notice BTW that there's a problem storing the window positions for the windows you have open there in the screenshot, because the user doesn't have write permissions for the extended attributes in those locations.

Yep, I think  the 'reuse an existing window' problem is solvable - I was thinking of having a singleton 'register' object that each MainWindow instance keeps up-to-date with its current path (and removes itself when closing). At the point where the new window is going to be opened, we query the register to see if there is an existing window with the path already open, and if so it gets a signal to raise itself. If there isn't, then we open a new window as is the case now. It'll probably be better as a separate commit?

**Comment by probonopd** [comment]
> Yep, I think the 'reuse an existing window' problem is solvable - I was thinking of having a singleton 'register' object that each MainWindow instance keeps up-to-date with its current path (and removes itself when closing). At the point where the new window is going to be opened, we query the register to see if there is an existing window with the path already open, and if so it gets a signal to raise itself. If there isn't, then we open a new window as is the case now. It'll probably be better as a separate commit?

That would be __excellent__. 
Please keep in mind the case of a folder being already open in a tab; in this case we should bring the window that contains the tab to the front and activate the tab.

A separate commit would be most welcome.

By the way, please let me know whether I may mention you on https://hellosystem.github.io/docs/developer/acknowledgements.

**Comment by moochris** [comment]
> Makes sense. The question is whether we should store the same information somewhere in ~ for the situations in which the location is not writable. (Here again, we should check how other systems are handling this situation.)

Yes, should be relatively easy to store under ~ somewhere instead if we can't write.

I'm not sure that other systems do handle this - at least Haiku doesn't have a workaround for the read-only system areas (due to their package FS).

If you think about CD-ROMs back in the classic Mac or Amiga days, these also didn't preserve spatial metadata if you moved window or icon positions.

> That would be __excellent__. 
> Please keep in mind the case of a folder being already open in a tab; in this case we should bring the window that contains the tab to the front and activate the tab.

OK, I'm sure that can be handled.

> A separate commit would be most welcome. I think that other commit should be enabled no matter whether the Filer is set to use Spatial Mode or not.

Sure, makes sense.

> By the way, please let me know whether I may mention you on https://hellosystem.github.io/docs/developer/acknowledgements.

Yes that would be great, thanks 🙂

**Comment by moochris** [comment]
OK, I think that's as much as I can do for the weekend :)

**Comment by probonopd** [comment]
Thank you very much @moochris. Excellent!

**Pull request merged**
